### ISSUE TITLE
holzschwert essen bringt Absturz

### ISSUE THREAD

**Issue by Toberfra** [blazeplex88/QuartalsAufgabe2024#1]
Ich habe versucht das Holzschwert zu Essen. Dabei ist die dialog.exe abgestürzt

**Comment by Toberfra** [comment]
In Version "ExE gefixt"

**Comment by Toberfra** [comment]
An Linus übergeben

**Comment by Toberfra** [comment]
Verdacht: Inventory.py Zeile 22 Version Exe

if choice in inv:   # in inv ist Holzschwert klein geschieben

dadurch kann choice = "holzschwert" sein

In Items.items ist "Holzschwert" gross geschrieben. dadurch stimmt der Schlüssel nicht und der KeyError wird erzeugt.

**Comment by R3DD4V** [comment]
Sollte gefixt sein
